// 在线用户获取
export type AdminDefinition024c169fd6317300a93e6c6ae52a0cb6 = {
	children?: Array<AdminDefinition024c169fd6317300a93e6c6ae52a0cb6>;
	// 编码
	code?: string;
	// 创建时间
	createTime?: string;
	// 创建人
	createdBy?: string;
	// 删除时间
	deleteTime?: number;
	// 主键
	id?: number;
	// 是否叶子:0-否,1-是
	leaf?: number;
	// 名称
	name?: string;
	// 排序
	orders?: number;
	// 上级部门ID
	parentId?: number;
	// 备注
	remark?: string;
	// 状态:0-禁用,1-启用
	statusFlag?: number;
	// 更新时间
	updateTime?: string;
	// 更新人
	updatedBy?: string;
};
