// 访问日志列表
export type Definition24c5d292941bca407fdba549081f6e23 = {
	// 访问来源地点
	accessAddress?: string;
	// 登录地址
	accessIp?: string;
	// 访问方法
	accessMethod?: string;
	// 访问入参
	accessParam?: string;
	// 访问返回值
	accessResult?: string;
	// 访问地址
	accessUri?: string;
	// 访问浏览器
	browser?: string;
	// 创建时间
	createTime?: string;
	// 创建人
	createdBy?: string;
	// 删除时间
	deleteTime?: number;
	// 姓名
	fullName?: string;
	// 主键
	id?: number;
	// 访问系统
	sysInfo?: string;
	// 管理员ID
	sysUserId?: number;
	// 访问耗时
	times?: number;
	// 更新时间
	updateTime?: string;
	// 更新人
	updatedBy?: string;
	// 账户名
	username?: string;
};
