// 菜单列表
export type Definitionad17cf51a443281f268168922cc18c74 = {
	// 绑定菜单数量
	bindingQuantity?: number;
	// 子菜单
	children?: Array<Definitionad17cf51a443281f268168922cc18c74>;
	// 创建时间
	createTime?: string;
	// 创建人
	createdBy?: string;
	// 主键
	id?: number;
	// 排序
	orders?: number;
	// 权限码
	permCode?: string;
	// 父ID
	pid?: number;
	// 备注
	remark?: string;
	// 标题
	title?: string;
	// 类型:0-模块,1-菜单,2-功能
	typeFlag?: number;
	// 更新时间
	updateTime?: string;
	// 更新人
	updatedBy?: string;
	path?: string;
	icon?: string;
};
