// 商品连表列表
export type GoodsBizGoodsDefinition1c3a9acf8a13ae399bd64a2dff497f56 = {
	// 年龄段
	age?: number;
	// 款号-不超过10
	alias?: string;
	// 品牌
	brandId?: number;
	// 小系列
	cat?: number;
	// 品类
	catAlias?: number;
	// 大类
	catType?: number;
	// 分类
	cateId?: number;
	// 物料类型
	classes?: number;
	// 加工工艺
	craft?: number;
	// 创建时间
	createTime?: string;
	// 创建人
	createdBy?: string;
	// 删除时间
	deleteTime?: number;
	// 面料
	fabric?: number;
	// 虚拟销量
	ficti?: number;
	// 商品id
	id?: number;
	// 主图
	image?: string;
	// 商品描述
	info?: string;
	// 关键字
	keyword?: string;
	// 长短装
	length?: number;
	// 吊牌价
	marketPrice?: number;
	// 底料
	material?: number;
	// 高价
	maxPrice?: number;
	// 低价
	minPrice?: number;
	// 产品款型
	modeling?: number;
	// 产品名
	name?: string;
	// 是否电子产品
	navigation?: number;
	// 下单类型
	orderType?: number;
	// 其他分类
	other?: number;
	// 指导价
	price?: number;
	// 产品季
	proSeason?: number;
	// 销售季节
	season?: number;
	// 系列
	series?: number;
	// 性别
	sex?: number;
	// 店铺id
	shopId?: number;
	// 权重
	sort?: number;
	// 来源 1-MDM 2-后台导入
	source?: number;
	// 执行标准
	standard?: number;
	// 商品状态：0-待上架、1-在架、2-下架
	status?: number;
	// 科技
	technology?: number;
	// 厚薄装
	thickness?: number;
	// 产品标题
	title?: string;
	// 上市日期
	upDate?: number;
	// 上下装
	upDown?: number;
	// 上架时间
	upTime?: number;
	// 更新时间
	updateTime?: string;
	// 更新人
	updatedBy?: string;
	// 针梭织
	weav?: number;
	// 销售年度
	year?: number;
};
