// 商品扩展表查单个
export type GoodsBizGoodsDefinition804adb07e3faa10a1e310dbb435bc72f = {
	// 年龄段
	age?: number;
	// 小系列
	cat?: number;
	// 品类
	catAlias?: number;
	// 大类
	catType?: number;
	// 物料类型
	classes?: number;
	// 加工工艺
	craft?: number;
	// 面料
	fabric?: number;
	// 虚拟销量
	ficti?: number;
	// 商品id
	id?: number;
	info?: string;
	// 长短装
	length?: number;
	// 底料
	material?: number;
	// 产品款型
	modeling?: number;
	// 是否电子产品
	navigation?: number;
	// 下单类型
	orderType?: number;
	// 其他分类
	other?: number;
	// 产品季
	proSeason?: number;
	// 销售季节
	season?: number;
	// 系列
	series?: number;
	// 性别
	sex?: number;
	// 权重
	sort?: number;
	// 来源 1-MDM 2-后台导入
	source?: number;
	// 执行标准
	standard?: number;
	// 科技
	technology?: number;
	// 厚薄装
	thickness?: number;
	// 上市日期
	upDate?: number;
	// 上下装
	upDown?: number;
	// 针梭织
	weav?: number;
	// 销售年度
	year?: number;
};
