image: reg.anta.cn/front/node:16.16-alpine3.15-git

stages:
  - build

build:
  stage: build
  tags:
    - nodejs
  only:
    - master
  cache:
    key: $CI_JOB_NAME
    paths:
      - .dll/
  before_script:
    - yarn  
  script:
    - npm run build
  after_script:
    - echo "deploy"
  artifacts:
    paths:
      - dist
    expire_in: 1 week
