image: reg.anta.cn/front/node:16.16-alpine3.15-git

stages:
  - prepare
  - build
  - deploy

prepare:
  stage: prepare
  tags:
    - nodejs
  only:
    - master
  script:
    - yarn

build:
  stage: build
  tags:
    - nodejs
  only:
    - master
  cache:
    key: $CI_JOB_NAME
    paths:
      - .dll
  script:
    - npx anta-cli vue-cli-service build
  artifacts:
    paths:
      - dist
    expire_in: 1 week

deploy:
  stage: deploy
  tags:
    - nodejs
  only:
    - master
  script:
    - echo "deploy"
